apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    tier: {{ .Values.service.tier }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: {{ .Values.service.name }}
    nodePort: {{ .Values.service.nodeport }}
  selector:
    app: {{ .Chart.Name }}
    tier: {{ .Values.service.tier }}
